on:
  workflow_run:
    workflows: ["Depend on this workflow"]
    types:
      - completed
    branches-ignore: ["main"]

jobs:
  depending-job:
    name: "Depending job"
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.event == 'pull_request'
    steps:
      - run: |
          echo ${{ github.event.workflow_run.event }}