name: Echo set environment variable
on: [push, pull_request]

jobs:
  
  test:
    name: "Echo env var"
    runs-on: ubuntu-latest
    steps:
      - name: Set environment for branch
        run: |
          if [[ "${{github.event_name}}" == "push" ]]; then
            echo "VALIDATE_ALL_CODEBASE=true" >> "$GITHUB_ENV"
          else
            echo "VALIDATE_ALL_CODEBASE=false" >> "$GITHUB_ENV"
          fi
      - run: echo "$VALIDATE_ALL_CODEBASE, $SECOND_VALIDATE"
        env: 
          SECOND_VALIDATE: ${{ github.event_name == 'push'}}