on:
    workflow_run:
        workflows: ["Run test suite"]
        types:
            - completed
  
jobs:
    upload-codecov:
        name: "Upload code coverage"
        runs-on: ubuntu-latest
        if: github.event.workflow_run.conclusion != 'skipped' && github.repository_owner == 'johannaengland'

        steps:
        - name: Checkout Code
          uses: actions/checkout@v4
          with:
            ref: ${{ github.event.workflow_run.head_sha }}

        - name: Download and Extract Artifacts
          env:
            GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          run: |
            mkdir -p artifacts && cd artifacts

            artifacts_url=${{ github.event.workflow_run.artifacts_url }}

            gh api "$artifacts_url" -q '.artifacts[] | [.name, .archive_download_url] | @tsv' | while read artifact
            do
              IFS=$'\t' read name url <<< "$artifact"
              gh api $url > "$name.zip"
              unzip -d "$name" "$name.zip"
            done

        - name: Echo PR number
          env: 
            PR_NUMBER: ${{ toJSON(github.event.workflow_run.pull_requests) }}
          run: |
            echo $PR_NUMBER

        - name: Read PR number file
          if: ${{ hashFiles('artifacts/extra/pr_number') != '' }}
          run: | 
            pr_number=$(cat artifacts/extra/pr_number)
            re='^[0-9]+$'
            if [[ $pr_number =~ $re ]] ; then
              echo "PR_NUMBER=$pr_number" >> $GITHUB_ENV
            fi

        - name: Read parent SHA file
          if: ${{ hashFiles('artifacts/extra/parent_sha') != '' }}
          run: | 
            parent_sha=$(cat artifacts/extra/parent_sha)
            re='[0-9a-f]{40}'
            if [[ $parent_sha =~ $re ]] ; then
              echo "PARENT_SHA=$parent_sha" >> $GITHUB_ENV
            fi
          

        - name: Upload to Codecov
          uses: codecov/codecov-action@v4
          with:
            fail_ci_if_error: true
            token: ${{ secrets.CODECOV_TOKEN }}
            verbose: true
            override_branch: ${{ github.event.workflow_run.head_branch}}
            override_commit: ${{ github.event.workflow_run.head_sha}}
            override_pr: ${{ env.PR_NUMBER }}
            override_build: ${{ github.event.workflow_run.id }}

        - name: "Publish test results"
          uses: EnricoMi/publish-unit-test-result-action@v2
          with:
            commit: ${{ github.event.workflow_run.head_sha }}
            check_name: "Test results"
            files: artifacts/**/*-results.xml

        