name: Echo set environment variable
on: [push, pull_request]

jobs:
  
  test:
    name: "Echo env var"
    runs-on: ubuntu-latest
    steps:
      - name: Set environment for branch
        run: |
          if [[ "${{github.event.name}}" == "push" ]]; then
            echo "::set-output name=VALIDATE_ALL_CODEBASE::true"
          else
            echo "::set-output name=VALIDATE_ALL_CODEBASE::false"
          fi
      - run: echo "$VALIDATE_ALL_CODEBASE"