name: Depending job

on:
  workflow_run:
    workflows: ["Depend on this workflow"]
    types:
      - completed

jobs:
  depending-job:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo The workflow we're dependent on has run