on:
  workflow_run:
    workflows: ["Depend on this workflow"]
    types:
      - completed
    branches-ignore: ["main"]

jobs:
  depending-job:
    name: "Depending job"
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ github.event.workflow_run }}