name: Run test suite

#########################################################
# Start the job on pushes to main and all pull requests #
#########################################################
on:
  push:
    branches: main
  pull_request:

###############
# Set the Job #
###############
jobs:
  tests:
    # Name the Job
    name: "Test on Python ${{ matrix.python-version}}"
    # Set the agent to run on
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Cache
        uses: actions/cache@v4
        id: cache
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-


      - name: "Set up Python ${{ matrix.python-version }}"
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install "tox<4" tox-gh-actions coverage
          sudo apt-get install -y --no-install-recommends snmp

      - name: Test with tox
        run: tox

      - name: Upload test reports (${{ matrix.python-version }})
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: reports-${{ matrix.python-version }}
          path: |
            reports/**/*
      
      - name: List all files to check context
        run: |
          search_dir="reports/"
          for entry in "$search_dir"/*
          do
            echo "$entry"
          done

  upload-pr-number:
    name: Save PR number in artifact
    runs-on: ubuntu-latest
    if: ${{ github.event.number && always() }}
    env:
      PR_NUMBER: ${{ github.event.number }}
    steps:
      - name: Make PR number file
        run: |
          mkdir -p ./pr
          echo $PR_NUMBER > ./pr/pr_number
      - name: Upload PR number file
        uses: actions/upload-artifact@v4
        with:
          name: pr_number
          path: pr/

      - name: Show GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
        